In [1]:
import numpy as np

In [5]:
np.logspace(-9, 3, 13)

array([  1.00000000e-09,   1.00000000e-08,   1.00000000e-07,
         1.00000000e-06,   1.00000000e-05,   1.00000000e-04,
         1.00000000e-03,   1.00000000e-02,   1.00000000e-01,
         1.00000000e+00,   1.00000000e+01,   1.00000000e+02,
         1.00000000e+03])

In [3]:
np.logspace(-2, 10, 13)

array([  1.00000000e-02,   1.00000000e-01,   1.00000000e+00,
         1.00000000e+01,   1.00000000e+02,   1.00000000e+03,
         1.00000000e+04,   1.00000000e+05,   1.00000000e+06,
         1.00000000e+07,   1.00000000e+08,   1.00000000e+09,
         1.00000000e+10])

In [9]:
from sklearn import svm
X = [[0,0], [1,0]]
y = [0,1]

In [10]:
clf = svm.SVC()
clf.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
clf.predict([[0,0]])

array([0])

In [14]:
clf.support_vectors_

array([[ 0.,  0.],
       [ 1.,  0.]])

In [15]:
clf.support_

array([0, 1])

In [16]:
clf.n_support_

array([1, 1])

## Multi class Classifier

In [35]:
X = [[0],[1],[2],[3]]
y = [0,1,2,3]

#clf = svm.SVC(decision_function_shape='ovr')
clf = svm.SVC(decision_function_shape='ovo')
clf.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [36]:
dec = clf.decision_function([[1]])

In [37]:
dec.shape[1]  # one over one decision function creates n*(n-1)/2 classifiers. in this case created 6 classifiers

6

## Linear SVM
Thid default tales decision function as "one over rest" ovr

In [39]:
lin_clf = svm.LinearSVC()
lin_clf.fit(X,y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [42]:
dec = lin_clf.decision_function([[1]])
dec.shape[1]

4

## Regression - SVR, NuSVR, LinearSVR

In [44]:
from sklearn import svm
X = [[0,0], [0,2]]
y = [0.2, 1.5]

reg = svm.SVR()
reg.fit(X,y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [45]:
reg.predict([1,1])

C:\Users\gvghonga\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 0.85])

In [ ]:
clf = svm.OneClassSVM